server:
  port: 8000

zuul:
  prefix: /api
  routes:
    register:
      path: /register/**
      serviceId: register-service
      strip-prefix: false
    serviceList:
      path: /services/**
      serviceId: schedule-service
      strip-prefix: false

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

