server:
  port: 8081

spring:
  profiles:
    active: dev

camel.springboot.shutdownTimeout: 2

---

spring:
  profiles: dev



---

spring:
  profiles: stage



---

spring:
  profiles: prod



---

spring:
  profiles: mock



---