cas:
    authn:
        accept:
            users: ''
        jdbc:
            query:
            -   dialect: org.hibernate.dialect.PostgreSQL95Dialect
                driver-class: org.postgresql.Driver
                field-disabled: disabled
                field-expired: expired
                field-password: password
                password: postgres
                password-encoder:
                    type: BCRYPT
                sql: SELECT * FROM users WHERE email = ?
                url: jdbc:postgresql://localhost:5432/cas
                user: postgres
    tgc:
        crypto:
            encryption:
                key: ${TGC_ENCRYPTION_KEY}
            signing:
                key: ${TGC_SIGNING_KEY}
    webflow:
        crypto:
            signing:
                key: ${WEBFLOW_SIGNING_KEY}
            encryption:
                key: ${WEBFLOW_ENCRYPTION_KEY}