server:
  port: 8081

spring:
  profiles:
    active: stage

camel.springboot.shutdownTimeout: 2

---

spring:
  profiles: dev

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute: file:data/dev/output
message: The DEV env

---

spring:
  profiles: stage

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute: file:data/stage/output
message: The STAGE env

---

spring:
  profiles: prod

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute: file:data/prod/output
message: The PROD env

---

spring:
  profiles: mock

startRoute: direct:input
fromRoute: file:data/input?delete=true&readLock=none
toRoute: mock:output
message: The DEV env

---